name: NodeJS with Grunt

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./nest
      run: |
        npm install
    - name: Build and test
      working-directory: ./nest
      run: |
        npm run build
        npm test
