name: NodeJS with Grunt

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./nest
      run: |
        npm install
    - name: Build and test
      working-directory: ./nest
      run: |
        npm run build
        npm test
    - name: zip create
      working-directory: ./nest
      run: zip -qq -r lsyhaha.zip .
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-ket-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: Upload to S3
      run: |
        aws s3 cp --region ap-northeast-2 ./lsyhaha.zip s3://lsyhaha/deploy/
    - name: Deploy
      run: |
        aws deploy create-deployment
        --application-name deploy-lsyhaha
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name deploy-lsyhaha
        --s3-location bucket=lsyhaha,bundleType=zip,key=deploy/lsyhaha.zip
