name: NodeJS with Grunt

on:
  push:
    branches: [ "development" ]

jobs:
  nest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install dependencies(nest)
    #   working-directory: ./nest
    #   run: |
    #     npm install
    # - name: Build and test(nest)
    #   working-directory: ./nest
    #   run: |
    #     npm run build
    #     npm test
    - name: zip create(nest)
      working-directory: ./nest
      run: |
        zip -r lsyhahanest.zip . -x "node_modules/*" "dist/*"
      shell: bash
    - name: Configure AWS credentials(nest)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Upload to S3(nest)
      working-directory: ./nest
      run: |
        aws s3 cp --region ap-northeast-2 ./lsyhahanest.zip s3://lsyhaha/deploy
    - name: Deploy(nest)
      run: aws deploy create-deployment
        --application-name lsyhaha
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name lsyhaha
        --s3-location bucket=lsyhaha,bundleType=zip,key=deploy/lsyhahanest.zip

  next:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies(next)
        working-directory: ./next
        run: |
          npm install
      - name: Build and test(next)
        working-directory: ./next
        run: |
          npm run build
      - name: zip create(next)
        working-directory: ./next
        run: |
          zip -r lsyhahanext.zip . -x "node_modules/*" "dist/*" ".next/*"
        shell: bash
      - name: Configure AWS credentials(next)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3(next)
        working-directory: ./next
        run: |
          aws s3 cp --region ap-northeast-2 ./lsyhahanext.zip s3://lsyhaha/deploy
      - name: Deploy(next)
        run: aws deploy create-deployment
          --application-name lsyhaha
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name lsyhaha
          --s3-location bucket=lsyhaha,bundleType=zip,key=deploy/lsyhahanext.zip